server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://instagram.cibpoowmrvlm.ap-northeast-2.rds.amazonaws.com:3306/aaa?autoReconnect=true # 변경해주세요
    username:  admin
    password:  jk670403
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전